### PR TITLE
Create all vision directories

### LINKED ISSUE #12: Create all /vision directories
Standardize and define directories under `/vision`:

* `/vision/pki`: certificates for puppet etc., not replicated, backed up
* `/vision/data`: application data, e.g. `/vision/data/nextcloud/`, replicated, backed up
* `/vision/{conf|etc}`: configuration for applications, e.g. `/vision/conf/redalert/config.json, managed via puppet, not replicated, backed up
* `/vision/logs`: application logs (if any), e.g. `/vision/logs/webshop/apf.log`, not replicated, not backed up, rotated
* ???

### PR DESCRIPTION
**Pull request by jacksgt**
Fixes #12

### CODE REVIEW

**Comment by jacksgt** [comment]
What about `/vision/pki`?

TODO: think about other directories

**Comment by martialblog** [comment]
I'll have a look at this on Friday.

**Comment by jacksgt** [comment]
When `/vision/logs` is not replicated, not managed and not backed up anyway, we might also just use `/var/log/`, right?

**Review by martialblog — COMMENTED** [review]
Checks out. I'll take care of the merge

**Pull request merged**
